[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.ruff]
target-version = "py311"
fix = true
include = ["*.py", "*.pyi", "**/pyproject.toml", "*.ipynb"]

[tool.isort]
profile = "black"
