name: 🐛 Bug Report
description: File a bug report for Python Project
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - evmckinney9
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report for our Python Project!
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      placeholder: Describe the bug you encountered here...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: Enter the software version
    validations:
      required: true
